### ISSUE TITLE
穿透版需要改相应python登录部分代码吗？

### ISSUE THREAD

**Issue by lbrein** [xystcz/PyCTPTrader#1]
hi，我用了你写的改进版，感觉很方便，用的也很稳定.....不过穿透版来了，不知道有什么需要注意的？谢谢

**Comment by xystcz** [comment]
PyCTP需要重新编译，Python部分代码需要修改。
相关修改已上传。

**Comment by lbrein** [comment]
非常感谢！

**Comment by lbrein** [comment]
18621335887 我的微信，希望多向你学习!

**Comment by lbrein** [comment]
linux 版本有些问题

**Comment by lbrein** [comment]
hi，再次感谢你改进的代码。  
    看穿版，windows测试验证都没问题了，包括正式版.... 不过linux版本有问题，如下图：


------------------ 原始邮件 ------------------
发件人: "xujunyong"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 下午2:02
收件人: "xystcz/PyCTPTrader"<PyCTPTrader@noreply.github.com>;
抄送: "lbrein421"<1953689193@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xystcz/PyCTPTrader] 穿透版需要改相应python登录部分代码吗？ (#1)




PyCTP需要重新编译，Python部分代码需要修改。
 相关修改已上传。g this because you authored the thread.

**Comment by xystcz** [comment]
图挂了
